//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int NewsId { get; set; }
        public string Username { get; set; }
        public string Content { get; set; }
        public bool isPublic { get; set; }
        public Nullable<int> DiscussId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Discuss Discuss { get; set; }
    }
}
